"""
CodeTrellis Auto-Generated Skills (A5.5)
=========================================

Generates AI-ready skills from the CodeTrellis Matrix. Each skill is a
pre-packaged context bundle that gives AI tools the knowledge needed to
perform specific tasks (e.g., "add-endpoint", "fix-issue", "add-model").

Skills are generated by analyzing the matrix sections to detect:
  - Available API patterns → "add-endpoint" skill
  - Database models → "add-model" skill
  - Test patterns → "add-test" skill
  - Error patterns → "fix-issue" skill
  - Component patterns → "add-component" skill
  - Configuration patterns → "update-config" skill

Each skill includes:
  - Name and description
  - Trigger condition (when the skill should be suggested)
  - Required context sections from the matrix
  - Pre-built instructions for the AI

Version: 1.0.0
Created: 20 February 2026
"""

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set


@dataclass
class Skill:
    """A generated skill that can be invoked by AI tools."""
    name: str
    description: str
    trigger: str
    context_sections: List[str]
    instructions: str
    category: str = "general"
    priority: int = 0  # Lower = higher priority

    def to_dict(self) -> Dict[str, any]:
        """Convert to dictionary for serialization."""
        return {
            "name": self.name,
            "description": self.description,
            "trigger": self.trigger,
            "context_sections": self.context_sections,
            "instructions": self.instructions,
            "category": self.category,
            "priority": self.priority,
        }

    def get_context(self, sections: Dict[str, str]) -> str:
        """
        Get the pre-loaded context for this skill from matrix sections.

        Args:
            sections: Parsed matrix sections

        Returns:
            Concatenated relevant section content
        """
        parts = [f"# Skill: {self.name}", f"# {self.description}", ""]
        for section_name in self.context_sections:
            if section_name in sections:
                parts.append(sections[section_name])
                parts.append("")
        parts.append(f"# Instructions:\n{self.instructions}")
        return "\n".join(parts)


# =============================================================================
# Skill Definitions — Templates that are activated based on matrix content
# =============================================================================

SKILL_TEMPLATES: List[Dict[str, any]] = [
    # ---- API / Endpoint Skills ----
    {
        "name": "add-endpoint",
        "description": "Add a new API endpoint following existing patterns",
        "trigger": "User asks to add a new API endpoint, route, or HTTP handler",
        "category": "api",
        "priority": 10,
        "detect_sections": [
            "HTTP_API", "ROUTES", "ROUTES_SEMANTIC", "CONTROLLERS",
            "PYTHON_API", "GO_API", "JAVA_API", "KOTLIN_API",
            "CSHARP_API", "RUST_API", "TS_API", "JS_API",
            "RUBY_API", "PHP_API", "SCALA_API", "SWIFT_API",
            "DART_API", "LUA_API", "C_API", "CPP_API",
            "R_API", "POWERSHELL_API", "BASH_API",
            "NEXT_SERVER_ACTIONS", "REMIX_ACTIONS", "ASTRO_API",
            "SOLIDJS_API", "QWIK_API", "PREACT_API", "LIT_API",
            "ALPINE_API", "HTMX_API", "STIMULUS_API",
            "STORYBOOK_API",
            "GO_GIN", "GO_ECHO", "GO_FIBER", "GO_CHI", "GO_GRPC",
        ],
        "context_sections": [
            "PROJECT", "SCHEMAS", "CONTROLLERS", "HTTP_API",
            "ROUTES", "MIDDLEWARE", "BEST_PRACTICES", "RUNBOOK",
        ],
        "instructions": (
            "Follow the existing endpoint patterns in the project. "
            "Match the controller/handler structure, DTO/validation patterns, "
            "middleware chain, and response format used by existing endpoints. "
            "Add appropriate tests following the project's test conventions."
        ),
    },
    {
        "name": "add-graphql-operation",
        "description": "Add a new GraphQL query, mutation, or subscription",
        "trigger": "User asks to add a GraphQL operation",
        "category": "api",
        "priority": 15,
        "detect_sections": ["GRAPHQL"],
        "context_sections": [
            "PROJECT", "GRAPHQL", "SCHEMAS", "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the existing GraphQL schema patterns. Match resolver structure, "
            "type definitions, and error handling patterns. Include input validation."
        ),
    },

    # ---- Model / Schema Skills ----
    {
        "name": "add-model",
        "description": "Add a new data model or schema following existing patterns",
        "trigger": "User asks to add a database model, entity, or schema",
        "category": "data",
        "priority": 10,
        "detect_sections": [
            "SCHEMAS", "DATABASE", "PYTHON_TYPES", "JAVA_MODELS",
            "KOTLIN_MODELS", "CSHARP_MODELS", "RUST_MODELS",
            "RUBY_MODELS", "PHP_MODELS", "TS_MODELS", "JS_MODELS",
            "SQL_TABLES", "DART_MODELS", "LUA_MODELS",
            "SWIFT_MODELS", "SCALA_MODELS", "GO_TYPES",
            "C_TYPES", "CPP_TYPES", "POWERSHELL_MODELS",
            "R_MODELS", "GO_GORM", "GO_SQLX",
        ],
        "context_sections": [
            "PROJECT", "SCHEMAS", "DATABASE", "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the existing model/entity patterns in the project. "
            "Match the ORM conventions (decorators, annotations, field types), "
            "include proper validation, relationships, and indexes. "
            "Create a migration if the project uses database migrations."
        ),
    },
    {
        "name": "add-migration",
        "description": "Create a database migration for schema changes",
        "trigger": "User asks to create a database migration",
        "category": "data",
        "priority": 20,
        "detect_sections": ["SQL_MIGRATIONS", "DATABASE"],
        "context_sections": [
            "DATABASE", "SQL_TABLES", "SQL_MIGRATIONS", "RUNBOOK",
        ],
        "instructions": (
            "Generate a reversible migration following the project's migration framework. "
            "Include both up and down migrations. Match existing naming conventions."
        ),
    },

    # ---- Component Skills ----
    {
        "name": "add-component",
        "description": "Add a new UI component following existing patterns",
        "trigger": "User asks to add a component, widget, or UI element",
        "category": "frontend",
        "priority": 10,
        "detect_sections": [
            "COMPONENTS", "REACT_COMPONENTS", "VUE_COMPONENTS",
            "SVELTE_COMPONENTS", "ANGULAR_SERVICES",
            "ASTRO_COMPONENTS", "LIT_COMPONENTS",
            "SOLIDJS_COMPONENTS", "QWIK_COMPONENTS", "PREACT_COMPONENTS",
            "ALPINE_COMPONENTS", "HTMX_ATTRIBUTES",
            "STIMULUS_CONTROLLERS",
            "STORYBOOK_STORIES", "STORYBOOK_COMPONENTS",
            "BOOTSTRAP_COMPONENTS", "MUI_COMPONENTS", "ANTD_COMPONENTS",
            "CHAKRA_COMPONENTS", "SHADCN_COMPONENTS", "RADIX_COMPONENTS",
            "SC_COMPONENTS", "EM_COMPONENTS",
        ],
        "context_sections": [
            "PROJECT", "COMPONENTS", "REACT_COMPONENTS", "REACT_HOOKS",
            "REACT_CONTEXT", "VUE_COMPONENTS", "VUE_COMPOSABLES",
            "SVELTE_COMPONENTS", "ASTRO_COMPONENTS",
            "SOLIDJS_COMPONENTS", "QWIK_COMPONENTS", "PREACT_COMPONENTS",
            "LIT_COMPONENTS", "ALPINE_COMPONENTS",
            "MUI_COMPONENTS", "ANTD_COMPONENTS", "CHAKRA_COMPONENTS",
            "SHADCN_COMPONENTS", "RADIX_COMPONENTS",
            "BOOTSTRAP_COMPONENTS", "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the existing component structure. Match naming conventions, "
            "state management patterns, prop types, styling approach, and "
            "accessibility patterns used in the project."
        ),
    },
    {
        "name": "add-hook",
        "description": "Add a custom React/Vue hook or composable",
        "trigger": "User asks to add a custom hook or composable",
        "category": "frontend",
        "priority": 15,
        "detect_sections": [
            "REACT_HOOKS", "HOOKS", "VUE_COMPOSABLES",
            "PREACT_HOOKS", "SOLIDJS_SIGNALS",
            "MUI_HOOKS", "ANTD_HOOKS", "CHAKRA_HOOKS", "SHADCN_HOOKS",
            "SWR_HOOKS", "RECOIL_HOOKS",
        ],
        "context_sections": [
            "PROJECT", "REACT_HOOKS", "HOOKS", "VUE_COMPOSABLES",
            "PREACT_HOOKS", "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the existing hook patterns. Match naming conventions (use* prefix), "
            "dependency patterns, cleanup logic, and return type structure."
        ),
    },
    {
        "name": "add-story",
        "description": "Add a Storybook story for a component",
        "trigger": "User asks to add a story, storybook story, or component story",
        "category": "frontend",
        "priority": 15,
        "detect_sections": [
            "STORYBOOK_STORIES", "STORYBOOK_COMPONENTS",
            "STORYBOOK_CONFIG", "STORYBOOK_API",
        ],
        "context_sections": [
            "PROJECT", "STORYBOOK_STORIES", "STORYBOOK_COMPONENTS",
            "STORYBOOK_CONFIG", "STORYBOOK_API", "STORYBOOK_ADDONS",
            "COMPONENTS", "REACT_COMPONENTS", "VUE_COMPONENTS",
            "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the existing story patterns in the project. "
            "Match the CSF version used, story naming conventions, arg types, "
            "decorators, and play function patterns. "
            "Include all meaningful component states as separate stories."
        ),
    },

    # ---- State Management Skills ----
    {
        "name": "add-store",
        "description": "Add a new state store (Redux/Zustand/Jotai/Pinia/etc.)",
        "trigger": "User asks to add a store, slice, or state atom",
        "category": "state",
        "priority": 10,
        "detect_sections": [
            "STORES", "REACT_STATE",
            "REDUX_STORES", "REDUX_SLICES",
            "ZUSTAND_STORES", "ZUSTAND_SELECTORS", "ZUSTAND_ACTIONS",
            "JOTAI_ATOMS", "JOTAI_SELECTORS",
            "RECOIL_ATOMS", "RECOIL_SELECTORS",
            "MOBX_OBSERVABLES", "MOBX_COMPUTEDS",
            "PINIA_STORES", "PINIA_GETTERS", "PINIA_ACTIONS",
            "NGRX_STORES", "NGRX_ACTIONS", "NGRX_EFFECTS", "NGRX_SELECTORS",
            "XSTATE_MACHINES", "XSTATE_STATES",
            "VALTIO_PROXIES", "VALTIO_SNAPSHOTS",
            "SVELTE_STORES",
            "SOLIDJS_STORES", "SOLIDJS_SIGNALS",
            "QWIK_SIGNALS", "PREACT_SIGNALS",
            "ALPINE_STORES",
        ],
        "context_sections": [
            "PROJECT", "STORES", "REACT_STATE",
            "REDUX_STORES", "REDUX_SLICES", "REDUX_SELECTORS",
            "ZUSTAND_STORES", "ZUSTAND_SELECTORS",
            "JOTAI_ATOMS", "RECOIL_ATOMS",
            "MOBX_OBSERVABLES", "PINIA_STORES", "PINIA_GETTERS",
            "NGRX_STORES", "NGRX_SELECTORS",
            "XSTATE_MACHINES", "VALTIO_PROXIES",
            "SVELTE_STORES", "SOLIDJS_STORES", "SOLIDJS_SIGNALS",
            "QWIK_SIGNALS", "PREACT_SIGNALS", "ALPINE_STORES",
            "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the existing state management patterns. Match the store library, "
            "action naming conventions, selector patterns, and middleware configuration."
        ),
    },

    # ---- Testing Skills ----
    {
        "name": "add-test",
        "description": "Add tests for existing code",
        "trigger": "User asks to add tests, write test cases, or improve coverage",
        "category": "testing",
        "priority": 10,
        "detect_sections": ["RUNBOOK", "PROJECT"],
        "context_sections": [
            "PROJECT", "RUNBOOK", "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the project's testing framework and conventions. Match test file "
            "naming, assertion style, mock/stub patterns, and test organization. "
            "Include edge cases and error scenarios. Check RUNBOOK for test commands."
        ),
    },

    # ---- Bug Fix Skills ----
    {
        "name": "fix-issue",
        "description": "Fix a bug with full project context",
        "trigger": "User reports a bug or asks to fix an issue",
        "category": "debugging",
        "priority": 5,
        "detect_sections": ["PROJECT"],  # Always available
        "context_sections": [
            "PROJECT", "ERROR_HANDLING", "ACTIONABLE_ITEMS", "TODOS",
            "BEST_PRACTICES", "RUNBOOK",
        ],
        "instructions": (
            "Analyze the bug in context of the project architecture. Check ERROR_HANDLING "
            "for existing error patterns, ACTIONABLE_ITEMS for related TODOs/FIXMEs. "
            "Propose a minimal, safe fix that matches existing error handling conventions. "
            "Include a test case to prevent regression."
        ),
    },

    # ---- Configuration Skills ----
    {
        "name": "update-config",
        "description": "Update project configuration",
        "trigger": "User asks to change config, environment variables, or settings",
        "category": "config",
        "priority": 15,
        "detect_sections": ["CONFIG_VARIABLES", "ENV_GAPS", "RUNBOOK"],
        "context_sections": [
            "PROJECT", "CONFIG_VARIABLES", "ENV_GAPS", "INFRASTRUCTURE", "RUNBOOK",
        ],
        "instructions": (
            "Review existing configuration patterns in CONFIG_VARIABLES. "
            "Check ENV_GAPS for undocumented environment variables. "
            "Ensure changes are consistent across all config files."
        ),
    },

    # ---- Infrastructure Skills ----
    {
        "name": "update-infrastructure",
        "description": "Modify Docker, CI/CD, or deployment configuration",
        "trigger": "User asks about Docker, CI/CD, deployment, or infrastructure",
        "category": "infra",
        "priority": 15,
        "detect_sections": ["INFRASTRUCTURE"],
        "context_sections": [
            "PROJECT", "INFRASTRUCTURE", "DATABASE", "SERVICE_MAP",
            "CONFIG_VARIABLES", "RUNBOOK",
        ],
        "instructions": (
            "Review existing infrastructure patterns. Match Docker conventions, "
            "CI/CD pipeline structure, and deployment patterns. Ensure changes "
            "are consistent with the service map and database configuration."
        ),
    },

    # ---- Security Skills ----
    {
        "name": "security-review",
        "description": "Review code for security issues",
        "trigger": "User asks about security, authentication, authorization, or vulnerabilities",
        "category": "security",
        "priority": 10,
        "detect_sections": ["SECURITY"],
        "context_sections": [
            "PROJECT", "SECURITY", "MIDDLEWARE", "HTTP_API",
            "CONFIG_VARIABLES", "BEST_PRACTICES",
        ],
        "instructions": (
            "Review the SECURITY section for existing auth mechanisms and flags. "
            "Check for missing authentication, authorization gaps, input validation, "
            "CORS configuration, and rate limiting. Follow BEST_PRACTICES for security."
        ),
    },

    # ---- Documentation Skills ----
    {
        "name": "document-api",
        "description": "Generate API documentation",
        "trigger": "User asks to document API endpoints or create API docs",
        "category": "docs",
        "priority": 20,
        "detect_sections": ["HTTP_API", "OPENAPI", "GRAPHQL"],
        "context_sections": [
            "PROJECT", "HTTP_API", "OPENAPI", "GRAPHQL",
            "SCHEMAS", "CONTROLLERS", "WEBSOCKET_EVENTS",
        ],
        "instructions": (
            "Generate comprehensive API documentation from the matrix data. "
            "Include endpoint descriptions, request/response schemas, "
            "authentication requirements, and example payloads."
        ),
    },

    # ---- Refactoring Skills ----
    {
        "name": "refactor-code",
        "description": "Refactor code following project patterns",
        "trigger": "User asks to refactor, restructure, or improve code quality",
        "category": "quality",
        "priority": 15,
        "detect_sections": ["PROJECT"],
        "context_sections": [
            "PROJECT", "OVERVIEW", "BEST_PRACTICES",
            "ACTIONABLE_ITEMS", "PROGRESS",
        ],
        "instructions": (
            "Follow BEST_PRACTICES when refactoring. Check ACTIONABLE_ITEMS for "
            "existing improvement opportunities. Maintain backward compatibility. "
            "Prefer small, reversible changes."
        ),
    },

    # ---- Styling Skills ----
    {
        "name": "add-style",
        "description": "Add styles using the project's CSS/styling approach",
        "trigger": "User asks to add styling, theming, or CSS changes",
        "category": "frontend",
        "priority": 15,
        "detect_sections": [
            "CSS_SELECTORS", "CSS_VARIABLES", "CSS_LAYOUT",
            "SASS_VARIABLES", "SASS_MIXINS", "LESS_VARIABLES", "LESS_MIXINS",
            "TAILWIND_CONFIG", "TAILWIND_UTILITIES", "TAILWIND_COMPONENTS",
            "POSTCSS_PLUGINS", "POSTCSS_CONFIG",
            "SC_COMPONENTS", "SC_THEME", "SC_MIXINS",
            "EM_COMPONENTS", "EM_STYLES", "EM_THEME",
            "MUI_THEME", "MUI_STYLES",
            "ANTD_THEME", "ANTD_STYLES",
            "CHAKRA_THEME", "CHAKRA_STYLES",
            "SHADCN_THEME", "SHADCN_STYLES",
            "BOOTSTRAP_THEME", "BOOTSTRAP_UTILITIES",
            "RADIX_THEME", "RADIX_STYLES",
        ],
        "context_sections": [
            "PROJECT", "CSS_SELECTORS", "CSS_VARIABLES",
            "SASS_VARIABLES", "SASS_MIXINS",
            "TAILWIND_CONFIG", "TAILWIND_UTILITIES",
            "SC_THEME", "EM_THEME", "MUI_THEME",
            "ANTD_THEME", "CHAKRA_THEME",
            "SHADCN_THEME", "BOOTSTRAP_THEME",
            "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the project's styling approach. Use existing CSS variables, "
            "design tokens, theme configuration, and utility patterns. "
            "Maintain consistent spacing, colors, and breakpoints."
        ),
    },

    # ---- Routing Skills ----
    {
        "name": "add-route",
        "description": "Add a new route or page to the application",
        "trigger": "User asks to add a new route, page, or navigation path",
        "category": "frontend",
        "priority": 12,
        "detect_sections": [
            "ROUTES", "ROUTES_SEMANTIC",
            "NEXT_PAGES", "NEXT_ROUTES",
            "REMIX_ROUTES", "REMIX_LOADERS",
            "VUE_ROUTING", "SVELTEKIT_ROUTING",
            "ASTRO_ROUTING", "QWIK_ROUTES",
        ],
        "context_sections": [
            "PROJECT", "ROUTES", "ROUTES_SEMANTIC",
            "NEXT_PAGES", "NEXT_ROUTES", "NEXT_SERVER_ACTIONS",
            "REMIX_ROUTES", "REMIX_LOADERS", "REMIX_ACTIONS",
            "VUE_ROUTING", "SVELTEKIT_ROUTING",
            "ASTRO_ROUTING", "QWIK_ROUTES",
            "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the existing routing structure. Match file/folder conventions, "
            "route naming patterns, data loading strategy (SSR/SSG/ISR), "
            "layout nesting, and middleware/guard patterns."
        ),
    },

    # ---- Data Fetching Skills ----
    {
        "name": "add-data-fetch",
        "description": "Add data fetching with TanStack Query/SWR/Apollo",
        "trigger": "User asks to add data fetching, query, or API call",
        "category": "data",
        "priority": 12,
        "detect_sections": [
            "TANSTACK_QUERIES", "TANSTACK_MUTATIONS",
            "SWR_HOOKS", "SWR_MUTATIONS",
            "APOLLO_QUERIES", "APOLLO_MUTATIONS",
            "NEXT_DATA_FETCHING", "REMIX_LOADERS",
            "SOLIDJS_RESOURCES", "QWIK_TASKS",
        ],
        "context_sections": [
            "PROJECT", "HTTP_API",
            "TANSTACK_QUERIES", "TANSTACK_MUTATIONS", "TANSTACK_CACHE",
            "SWR_HOOKS", "SWR_MUTATIONS", "SWR_CACHE",
            "APOLLO_QUERIES", "APOLLO_MUTATIONS", "APOLLO_CACHE",
            "NEXT_DATA_FETCHING", "REMIX_LOADERS",
            "SOLIDJS_RESOURCES", "QWIK_TASKS",
            "BEST_PRACTICES",
        ],
        "instructions": (
            "Follow the project's data fetching patterns. Match query key conventions, "
            "cache invalidation strategy, error handling, loading states, "
            "and optimistic update patterns."
        ),
    },
]


class SkillsGenerator:
    """
    Generates skills from the CodeTrellis Matrix.

    Analyzes which matrix sections are present and generates appropriate
    skills that AI tools can use for context-aware task completion.
    """

    def __init__(self, sections: Dict[str, str]) -> None:
        """
        Initialize the skills generator.

        Args:
            sections: Parsed matrix sections {name: content}
        """
        self._sections = sections
        self._available_section_names: Set[str] = set(
            k for k in sections.keys() if k != "_PREAMBLE"
        )

    def generate(self) -> List[Skill]:
        """
        Generate skills based on available matrix sections.

        Returns:
            List of generated skills, sorted by priority
        """
        skills: List[Skill] = []

        for template in SKILL_TEMPLATES:
            # Check if any of the detection sections are present
            detect_sections = template["detect_sections"]
            has_content = any(
                sname in self._available_section_names
                for sname in detect_sections
            )

            if not has_content:
                continue

            # Filter context sections to only include available ones
            available_context = [
                s for s in template["context_sections"]
                if s in self._available_section_names
            ]

            # Enrich instructions with project-specific info
            instructions = self._enrich_instructions(template)

            skill = Skill(
                name=template["name"],
                description=template["description"],
                trigger=template["trigger"],
                context_sections=available_context,
                instructions=instructions,
                category=template.get("category", "general"),
                priority=template.get("priority", 50),
            )
            skills.append(skill)

        # Sort by priority (lower = higher priority)
        skills.sort(key=lambda s: s.priority)
        return skills

    def _enrich_instructions(self, template: Dict[str, any]) -> str:
        """
        Enrich skill instructions with project-specific context.

        Appends detected patterns from the matrix to make instructions
        more specific to the actual project.
        """
        base = template["instructions"]
        enrichments: List[str] = []

        # Detect project type
        if "PROJECT" in self._sections:
            project_content = self._sections["PROJECT"]
            type_match = re.search(r'type=(.+)', project_content)
            if type_match:
                enrichments.append(f"Project type: {type_match.group(1).strip()}")
            stack_match = re.search(r'stack=(.+)', project_content)
            if stack_match:
                enrichments.append(f"Tech stack: {stack_match.group(1).strip()}")

        # Detect testing framework
        if "RUNBOOK" in self._sections:
            runbook = self._sections["RUNBOOK"]
            if "pytest" in runbook.lower():
                enrichments.append("Testing framework: pytest")
            elif "jest" in runbook.lower():
                enrichments.append("Testing framework: Jest")
            elif "go test" in runbook.lower():
                enrichments.append("Testing framework: go test")

        # Detect database
        if "DATABASE" in self._sections:
            db_content = self._sections["DATABASE"]
            dbs = re.findall(r'db:(\S+)', db_content)
            if dbs:
                enrichments.append(f"Databases: {', '.join(set(dbs))}")

        if enrichments:
            return f"{base}\n\nDetected context:\n" + "\n".join(f"  - {e}" for e in enrichments)
        return base

    def get_skill_by_name(self, name: str) -> Optional[Skill]:
        """
        Get a specific skill by name.

        Args:
            name: Skill name (e.g., "add-endpoint")

        Returns:
            Skill object or None if not found/applicable
        """
        skills = self.generate()
        for skill in skills:
            if skill.name == name:
                return skill
        return None

    def get_skill_context(self, skill_name: str) -> Optional[str]:
        """
        Get the full context for a skill (sections + instructions).

        Args:
            skill_name: Skill name

        Returns:
            Pre-loaded context string or None
        """
        skill = self.get_skill_by_name(skill_name)
        if skill is None:
            return None
        return skill.get_context(self._sections)

    def list_skill_names(self) -> List[str]:
        """Get list of available skill names."""
        return [s.name for s in self.generate()]

    def to_claude_skills_format(self) -> List[Dict[str, str]]:
        """
        Export skills in Claude Code .claude/skills/ format.

        Returns:
            List of skill definitions suitable for writing to
            .claude/skills/{name}.md files
        """
        skills = self.generate()
        result = []
        for skill in skills:
            content_parts = [
                f"# {skill.name}",
                "",
                f"> {skill.description}",
                "",
                f"**Trigger:** {skill.trigger}",
                "",
                "## Context Sections",
                "",
            ]
            for section_name in skill.context_sections:
                content_parts.append(f"- `{section_name}`")
            content_parts.extend([
                "",
                "## Instructions",
                "",
                skill.instructions,
            ])
            result.append({
                "name": skill.name,
                "filename": f"{skill.name}.md",
                "content": "\n".join(content_parts),
            })
        return result
